source 'https://rubygems.org'

ruby '~> 3.2.0'

# Core Rails
gem 'rails'
gem 'sprockets-rails'

# Database
gem 'mysql2'

# Server
gem 'puma'

# Background Jobs
gem 'sidekiq'
gem 'sidekiq-scheduler'

# Admin Interface
gem 'activeadmin'
gem 'devise'

# State Machine
gem 'aasm'

# JSON Serialization
gem 'active_model_serializers'

# CORS
gem 'rack-cors'

# Environment Variables
gem 'dotenv-rails', groups: [:development, :test]

# Store models (for JSON columns)
gem 'store_model'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'listen'
  gem 'spring'
  gem 'annotate'
  gem 'bootsnap'
end
