source 'https://rubygems.org'

ruby '~> 3.2.0'

# Core Rails
gem 'rails', '~> 7.1.0'

# Database
gem 'mysql2', '~> 0.5'

# Server
gem 'puma', '~> 6.0'

# Background Jobs
gem 'sidekiq', '~> 7.0'
gem 'sidekiq-scheduler', '~> 5.0'

# Admin Interface
gem 'activeadmin', '~> 3.0'
gem 'devise', '~> 4.9'

# State Machine
gem 'aasm', '~> 5.5'

# JSON Serialization
gem 'active_model_serializers', '~> 0.10.0'

# CORS
gem 'rack-cors'

# Environment Variables
gem 'dotenv-rails', groups: [:development, :test]

# Store models (for JSON columns)
gem 'store_model', '~> 2.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.0'
end

group :development do
  gem 'listen', '~> 3.8'
  gem 'spring'
  gem 'annotate', '~> 3.2'
end
